CREATE TABLE IF NOT EXISTS tenants (id BIGSERIAL PRIMARY KEY, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, brand_name TEXT, brand_tagline TEXT DEFAULT 'We deliver.', brand_primary_color TEXT DEFAULT '#8b5cf6', brand_accent_color TEXT DEFAULT '#ec4899', brand_favicon_emoji TEXT DEFAULT '🧴', brand_welcome_message TEXT, ai_system_prompt TEXT, ai_language TEXT DEFAULT 'en', ai_tone TEXT DEFAULT 'friendly', ai_enabled BOOLEAN DEFAULT true, plan TEXT DEFAULT 'free', fb_page_access_token TEXT, fb_app_secret TEXT, fb_verify_token TEXT, fb_page_id TEXT, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS conversations (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), sender_id TEXT NOT NULL, name TEXT, status TEXT DEFAULT 'active', tags JSONB DEFAULT '[]', notes TEXT, custom_fields JSONB DEFAULT '{}', is_bot_enabled BOOLEAN DEFAULT true, last_activity_at TIMESTAMPTZ, updated_at TIMESTAMPTZ DEFAULT NOW(), created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(tenant_id, sender_id));
CREATE TABLE IF NOT EXISTS messages (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), conversation_id BIGINT REFERENCES conversations(id), sender_type TEXT NOT NULL, message_type TEXT DEFAULT 'text', content TEXT, media_url TEXT, mid TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS orders (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), conversation_id BIGINT, customer_name TEXT, status TEXT DEFAULT 'new', payment_status TEXT DEFAULT 'pending', amount DECIMAL(10,2), custom_fields JSONB DEFAULT '{}', notes TEXT, updated_at TIMESTAMPTZ DEFAULT NOW(), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ledger_entries (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), date DATE, description TEXT, category TEXT, amount DECIMAL(10,2), type TEXT DEFAULT 'expense', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS automations (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), name TEXT, trigger_type TEXT, trigger_value TEXT, steps JSONB DEFAULT '[]', is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS faqs (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), question TEXT, answer TEXT, keywords TEXT, category TEXT DEFAULT 'general', sort_order INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS quick_replies (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), label TEXT, message TEXT, sort_order INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_custom_fields (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), field_key TEXT NOT NULL, field_label TEXT, field_type TEXT DEFAULT 'text', field_options JSONB DEFAULT '[]', apply_to TEXT DEFAULT 'orders', sort_order INT DEFAULT 0, UNIQUE(tenant_id, field_key));
CREATE TABLE IF NOT EXISTS bot_flow_steps (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), step_key TEXT NOT NULL, step_label TEXT, step_type TEXT DEFAULT 'text_input', prompt_message TEXT, button_choices JSONB DEFAULT '[]', next_step TEXT, input_variable TEXT, sort_order INT DEFAULT 0, UNIQUE(tenant_id, step_key));
CREATE TABLE IF NOT EXISTS bot_flow_state (conversation_id BIGINT PRIMARY KEY REFERENCES conversations(id), current_step TEXT, collected_data JSONB DEFAULT '{}', is_complete BOOLEAN DEFAULT false, started_at TIMESTAMPTZ DEFAULT NOW(), completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS tenant_order_statuses (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), status_key TEXT NOT NULL, status_label TEXT, color TEXT DEFAULT '#4d8ef7', sort_order INT DEFAULT 0, UNIQUE(tenant_id, status_key));
CREATE TABLE IF NOT EXISTS tenant_finance_categories (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), category_key TEXT NOT NULL, category_label TEXT, type TEXT DEFAULT 'expense', color TEXT DEFAULT '#8b90a0', UNIQUE(tenant_id, category_key, type));
CREATE TABLE IF NOT EXISTS tenant_tags (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), tag_key TEXT NOT NULL, tag_label TEXT, color TEXT DEFAULT '#8b5cf6', UNIQUE(tenant_id, tag_key));
CREATE TABLE IF NOT EXISTS media_assets (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), category TEXT DEFAULT 'general', filename TEXT, url TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS message_templates (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), name TEXT, template_type TEXT DEFAULT 'text', content JSONB DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS audit_log (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id), user_email TEXT, action TEXT, details JSONB DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS global_settings (key TEXT PRIMARY KEY, value JSONB, updated_at TIMESTAMPTZ DEFAULT NOW());

INSERT INTO global_settings (key, value) VALUES ('schema_version', '"pawperfume-v2"') ON CONFLICT DO NOTHING;
INSERT INTO tenants (slug, name, brand_name, brand_tagline, brand_primary_color, brand_accent_color, brand_favicon_emoji, brand_welcome_message, ai_system_prompt, ai_language, ai_tone, plan)
VALUES ('default', 'PawPerfume', 'PawPerfume', 'Premium Scents, Delivered', '#8b5cf6', '#ec4899', '🧴', 'Welcome to PawPerfume! 🧴 Premium perfumes delivered to your door. How can we help?', 'You are the friendly assistant of PawPerfume, a premium perfume business. Keep replies short. Help customers choose scents, place orders, and answer questions.', 'en', 'friendly', 'pro') ON CONFLICT DO NOTHING;

INSERT INTO tenant_custom_fields (tenant_id, field_key, field_label, field_type, field_options, apply_to, sort_order) VALUES (1, 'scent_preference', 'Scent Preference', 'select', '["Floral","Woody","Fresh / Citrus","Oriental","Fruity","Any"]', 'orders', 0) ON CONFLICT DO NOTHING;
INSERT INTO tenant_custom_fields (tenant_id, field_key, field_label, field_type, field_options, apply_to, sort_order) VALUES (1, 'bottle_size', 'Bottle Size', 'select', '["30ml (₱599)","50ml (₱899)","100ml (₱1,499)","Sample Set (₱299)"]', 'orders', 1) ON CONFLICT DO NOTHING;
INSERT INTO tenant_custom_fields (tenant_id, field_key, field_label, field_type, field_options, apply_to, sort_order) VALUES (1, 'delivery_address', 'Delivery Address', 'text', '[]', 'orders', 2) ON CONFLICT DO NOTHING;

INSERT INTO bot_flow_steps (tenant_id, step_key, step_label, step_type, prompt_message, next_step, input_variable, sort_order) VALUES (1, 'greet', 'Welcome', 'auto', 'Welcome to PawPerfume! 🧴 Let me help you find your perfect scent.', 'ask_name', null, 0) ON CONFLICT DO NOTHING;
INSERT INTO bot_flow_steps (tenant_id, step_key, step_label, step_type, prompt_message, next_step, input_variable, sort_order) VALUES (1, 'ask_name', 'Ask Name', 'text_input', 'What is your name?', 'ask_scent', 'customer_name', 1) ON CONFLICT DO NOTHING;
INSERT INTO bot_flow_steps (tenant_id, step_key, step_label, step_type, prompt_message, button_choices, next_step, input_variable, sort_order) VALUES (1, 'ask_scent', 'Scent Preference', 'button_choice', 'What type of scent do you prefer? 🌸', '[{"label":"Floral","next_step":"ask_size"},{"label":"Woody","next_step":"ask_size"},{"label":"Fresh / Citrus","next_step":"ask_size"},{"label":"Oriental","next_step":"ask_size"},{"label":"Fruity","next_step":"ask_size"},{"label":"Not Sure","next_step":"ask_size"}]', null, 'scent_preference', 2) ON CONFLICT DO NOTHING;
INSERT INTO bot_flow_steps (tenant_id, step_key, step_label, step_type, prompt_message, button_choices, next_step, input_variable, sort_order) VALUES (1, 'ask_size', 'Bottle Size', 'button_choice', 'What size would you like? 🧴', '[{"label":"30ml - ₱599","next_step":"ask_address"},{"label":"50ml - ₱899","next_step":"ask_address"},{"label":"100ml - ₱1,499","next_step":"ask_address"},{"label":"Sample Set - ₱299","next_step":"ask_address"}]', null, 'bottle_size', 3) ON CONFLICT DO NOTHING;
INSERT INTO bot_flow_steps (tenant_id, step_key, step_label, step_type, prompt_message, next_step, input_variable, sort_order) VALUES (1, 'ask_address', 'Delivery Address', 'text_input', 'Where should we deliver? 🏠', 'confirm', 'delivery_address', 4) ON CONFLICT DO NOTHING;
INSERT INTO bot_flow_steps (tenant_id, step_key, step_label, step_type, prompt_message, next_step, input_variable, sort_order) VALUES (1, 'confirm', 'Confirmation', 'auto', 'Thank you! Our team will confirm your order shortly. 🧴✨', null, null, 5) ON CONFLICT DO NOTHING;

INSERT INTO faqs (tenant_id, question, answer, keywords) VALUES (1, 'How much are your perfumes?', 'Sample Sets from ₱299 • 30ml ₱599 • 50ml ₱899 • 100ml ₱1,499. Free delivery on orders ₱1,000+!', 'price,cost,magkano') ON CONFLICT DO NOTHING;
INSERT INTO faqs (tenant_id, question, answer, keywords) VALUES (1, 'What scents are available?', 'We offer Floral 🌸, Woody 🌲, Fresh/Citrus 🍋, Oriental 🌙, and Fruity 🍓 scents. Custom blends also available!', 'scent,smell,amoy') ON CONFLICT DO NOTHING;
INSERT INTO faqs (tenant_id, question, answer, keywords) VALUES (1, 'How long is delivery?', 'Metro Manila: 1-2 days. Provincial: 3-5 days via LBC/J&T.', 'delivery,shipping,tagal') ON CONFLICT DO NOTHING;
INSERT INTO faqs (tenant_id, question, answer, keywords) VALUES (1, 'How do I pay?', 'GCash, Maya, BPI/BDO transfer, and COD (Metro Manila only).', 'payment,pay,gcash,maya') ON CONFLICT DO NOTHING;

INSERT INTO quick_replies (tenant_id, label, message) VALUES (1, '👋 Welcome', 'Welcome to PawPerfume! 🧴 Premium perfumes delivered to your door.') ON CONFLICT DO NOTHING;
INSERT INTO quick_replies (tenant_id, label, message) VALUES (1, '💰 Pricing', 'Our prices: Sample Set ₱299 • 30ml ₱599 • 50ml ₱899 • 100ml ₱1,499') ON CONFLICT DO NOTHING;

INSERT INTO tenant_order_statuses (tenant_id, status_key, status_label, color, sort_order) VALUES (1, 'new', 'New', '#4d8ef7', 1) ON CONFLICT DO NOTHING;
INSERT INTO tenant_order_statuses (tenant_id, status_key, status_label, color, sort_order) VALUES (1, 'confirmed', 'Confirmed', '#f59e0b', 2) ON CONFLICT DO NOTHING;
INSERT INTO tenant_order_statuses (tenant_id, status_key, status_label, color, sort_order) VALUES (1, 'preparing', 'Preparing', '#8b5cf6', 3) ON CONFLICT DO NOTHING;
INSERT INTO tenant_order_statuses (tenant_id, status_key, status_label, color, sort_order) VALUES (1, 'delivered', 'Delivered', '#10b981', 4) ON CONFLICT DO NOTHING;

INSERT INTO tenant_tags (tenant_id, tag_key, tag_label, color) VALUES (1, 'vip', 'VIP', '#f59e0b') ON CONFLICT DO NOTHING;
INSERT INTO tenant_tags (tenant_id, tag_key, tag_label, color) VALUES (1, 'repeat', 'Repeat', '#10b981') ON CONFLICT DO NOTHING;
INSERT INTO tenant_tags (tenant_id, tag_key, tag_label, color) VALUES (1, 'new', 'New', '#4d8ef7') ON CONFLICT DO NOTHING;
INSERT INTO tenant_tags (tenant_id, tag_key, tag_label, color) VALUES (1, 'urgent', 'Urgent', '#ef4444') ON CONFLICT DO NOTHING;
